#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.0b5 on Mon Jan 14 10:35:25 2019
#

import wx




class _308418605_MyMenuBar(wx.MenuBar):
    def __init__(self, *args, **kwds):
        wx.MenuBar.__init__(self, *args, **kwds)
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "item", "")
        wxglade_tmp_menu.Append(wx.NewId(), "item", "")
        self.Append(wxglade_tmp_menu, "item")
        self.--- = wx.Menu()
        self.Append(self.---, "---")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu_sub = wx.Menu()
        wxglade_tmp_menu_sub.Append(wx.NewId(), "item", "")
        wxglade_tmp_menu_sub.Append(wx.NewId(), "item", "")
        wxglade_tmp_menu.Append(wx.NewId(), "item", wxglade_tmp_menu_sub, "")
        wxglade_tmp_menu.Append(wx.NewId(), "item", "")
        self.Append(wxglade_tmp_menu, "item")

        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        pass

    def __do_layout(self):
        pass


class MyAppy(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

if __name__ == "__main__":
    appy = MyAppy(0)
    appy.MainLoop()
