import wx

if "wxMac" in wx.PlatformInfo:
    DEFAULT_COMMENT_FONT_SIZE = 14
    DEFAULT_CLASS_HEADING_FONT_SIZE = 14
    DEFAULT_CLASS_ATTRS_METHS_FONT_SIZE = 10
    DEFAULT_ASCII_UML_FONT_SIZE = 14
elif "wxGTK" in wx.PlatformInfo:
    DEFAULT_COMMENT_FONT_SIZE = 10
    DEFAULT_CLASS_HEADING_FONT_SIZE = 12
    DEFAULT_CLASS_ATTRS_METHS_FONT_SIZE = 9
    DEFAULT_ASCII_UML_FONT_SIZE = 10
else:  # windows
    DEFAULT_COMMENT_FONT_SIZE = 10
    DEFAULT_CLASS_HEADING_FONT_SIZE = 12
    DEFAULT_CLASS_ATTRS_METHS_FONT_SIZE = 10
    DEFAULT_ASCII_UML_FONT_SIZE = 10
