// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

unit unit_TestCase02;

interface

uses
    unit_TestCase, unit_PlayheadMediator;

type

TestCase02 = class(TestCase)
public
    _goto : PlayheadMediator;

    procedure setUp(); virtual;
    procedure CalcAmountOfTimeInStoryline(); virtual;
    procedure EnsureSanity(); virtual;
    procedure check01(); virtual;
end;


implementation

procedure TestCase02.setUp();
begin
end;

procedure TestCase02.CalcAmountOfTimeInStoryline();
begin
end;

procedure TestCase02.EnsureSanity();
begin
end;

procedure TestCase02.check01();
begin
end;


end.

