// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

unit unit_UniqueList;

interface

uses
    unit_list;

type

UniqueList = class(list)
public
    procedure append(); virtual;
    procedure __add__(); virtual;
    procedure __iadd__(); virtual;
end;


implementation

procedure UniqueList.append();
begin
end;

procedure UniqueList.__add__();
begin
end;

procedure UniqueList.__iadd__();
begin
end;


end.

