// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

unit unit_TimePlayAPI;

interface

uses
    unit_PlayAPI;

type

TimePlayAPI = class(PlayAPI)
public
    procedure GetCurrentValue(); virtual;
    procedure GetMaxValue(); virtual;
    procedure JumpToValue(); virtual;
    procedure _DeriveOtherPlayheadPositionsFrom(); virtual;
    procedure _SetOtherPlayheadsTo(); virtual;
    procedure SynchroniseOtherPlayheads(); virtual;
end;


implementation

procedure TimePlayAPI.GetCurrentValue();
begin
end;

procedure TimePlayAPI.GetMaxValue();
begin
end;

procedure TimePlayAPI.JumpToValue();
begin
end;

procedure TimePlayAPI._DeriveOtherPlayheadPositionsFrom();
begin
end;

procedure TimePlayAPI._SetOtherPlayheadsTo();
begin
end;

procedure TimePlayAPI.SynchroniseOtherPlayheads();
begin
end;


end.

