// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

unit unit_TestCase01;

interface

uses
    unit_TestCase, unit_PlayheadMediator;

type

TestCase01 = class(TestCase)
public
    _goto : PlayheadMediator;

    procedure setUp(); virtual;
    procedure checkInit(); virtual;
    procedure checkStartNoItemsNormal(); virtual;
    procedure checkStartNoItemsAndGoPreviousNormal(); virtual;
    procedure checkStartOneItemNormal(); virtual;
    procedure checkBasicMovementSynch01Normal(); virtual;
    procedure checkBasicMovementSynch02Normal(); virtual;
    procedure checkMaxValue(); virtual;
    procedure checkJumpToAndValidateCurrentValueNormal(); virtual;
    procedure checkIsEmptyNormal(); virtual;
    procedure checkByTimeAndEventPositioningNormal(); virtual;
    procedure checkByTurnPositioningNormal(); virtual;
    procedure checkByTimeAndEventPositioningNormal02(); virtual;
end;


implementation

procedure TestCase01.setUp();
begin
end;

procedure TestCase01.checkInit();
begin
end;

procedure TestCase01.checkStartNoItemsNormal();
begin
end;

procedure TestCase01.checkStartNoItemsAndGoPreviousNormal();
begin
end;

procedure TestCase01.checkStartOneItemNormal();
begin
end;

procedure TestCase01.checkBasicMovementSynch01Normal();
begin
end;

procedure TestCase01.checkBasicMovementSynch02Normal();
begin
end;

procedure TestCase01.checkMaxValue();
begin
end;

procedure TestCase01.checkJumpToAndValidateCurrentValueNormal();
begin
end;

procedure TestCase01.checkIsEmptyNormal();
begin
end;

procedure TestCase01.checkByTimeAndEventPositioningNormal();
begin
end;

procedure TestCase01.checkByTurnPositioningNormal();
begin
end;

procedure TestCase01.checkByTimeAndEventPositioningNormal02();
begin
end;


end.

