name: Pynsource Snap

on:
  push:
    # branches: [ master ]
    # tags: ['build-test-*']
    tags: ['pre-*', 'version-*']

jobs:
  my-snap-building-job:
    runs-on: ubuntu-18.04  # ubuntu-20.04 breaks

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/snapcraft-action
      - name: Install Snapcraft, LXD and set Auth
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true
          snapcraft_token: ${{ secrets.snapcraft_token }}

      # You can now run Snapcraft shell commands
      - name: Use Snapcraft - show help
        run: snapcraft --help

      - name: Build snap
        run: |
          sg lxd -c 'snapcraft --use-lxd'
          ls -l
          # unsquashfs -l *.snap

      - name: Save snap as artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap_artifact
          path: ./*.snap

      # https://github.com/samuelmeuli/action-snapcraft/issues/28
      # Uploads the snap to edge channel, test via: sudo snap refresh pynsource --edge
      - name: Snap upload
        id: snapcraft
        run: |
          snapcraft upload *.snap --release edge
