# Run unittests under multiple OS's and multiple Pythons.
# I also have a travis integration running these same tests under Python 3.9 on xenial (Ubuntu 16.04) - see .travis.yml 
name: Unittests
on:
  push:
    branches: [ master, gh-building ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .requirement-extras/requirements-travis.txt
    - name: Test with unittest
      shell: bash
      run: |
        export TRAVIS=1
        sh -c 'cd src && mkdir tests/logs && ./bin/testall'
