// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class PlayAPI {
    public  variant mediator;
    public  variant playhead;
    public  variant turnMgr;
    public void __init__() {
    }
    public void IsEmpty() {
    }
    public void IsMoreToPlay() {
    }
    public void Start() {
    }
    public void Endd() {
    }
    public void Next() {
    }
    public void Previous() {
    }
    public void _GetCurrentPosition() {
    }
    public void GetCurrentValue() {
    }
    public void _GetMaxPosition() {
    }
    public void GetMaxValue() {
    }
    public void _JumpToPosition() {
    }
    public void JumpToValue() {
    }
    public void NotifyOfInsert() {
    }
    public void NotifyPositionNowValid() {
    }
    public void SynchroniseOtherPlayheads() {
    }
    public void _FindLastEventWithTimeElseMostRecentEventLessthanTime() {
    }
    public void _FindLastEventWithTimeElseMostRecentEventLessthanTime_ORI() {
    }
    public void _EnsureMaxTimeCorrespondsToMaxTurn() {
    }
    public void _GetPositionToSyncTo() {
    }
}
