// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class TimePlayAPI extends PlayAPI {
    public void GetCurrentValue() {
    }
    public void GetMaxValue() {
    }
    public void JumpToValue() {
    }
    public void _DeriveOtherPlayheadPositionsFrom() {
    }
    public void _SetOtherPlayheadsTo() {
    }
    public void SynchroniseOtherPlayheads() {
    }
}
