#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Mon Mar 14 20:44:34 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class MyNotebook(wx.Notebook):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyNotebook.__init__
        kwds["style"] = 0
        wx.Notebook.__init__(self, *args, **kwds)
        self.notebook_1_pane_1 = wx.Panel(self, -1)
        self.text_ctrl_1 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.button_1 = wx.Button(self.notebook_1_pane_1, -1, "button_1")
        self.button_2 = wx.Button(self.notebook_1_pane_1, -1, "button_2")
        self.notebook_1_pane_2 = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyNotebook.__set_properties
        self.AddPage(self.notebook_1_pane_1, "tab1")
        self.AddPage(self.notebook_1_pane_2, "tab2")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyNotebook.__do_layout
        sizer_222 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_222.Add((20, 20), 0, 0, 0)
        sizer_222.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_222.Add((20, 60), 0, 0, 0)
        sizer_2.Add(self.button_1, 0, 0, 0)
        sizer_2.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_2.Add(self.button_2, 0, 0, 0)
        sizer_222.Add(sizer_2, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_222)
        # end wxGlade

# end of class MyNotebook


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = MyNotebook(self, -1)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(12, "bbbbbb", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "AAAAAA")
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "item")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = ["frame_1_statusbar"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
