// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

public class UniqueList extends list {
    public void append() {
    }
    public void __add__() {
    }
    public void __iadd__() {
    }
}
