
(*
  ModuleMethods = ['suite', 'main']
*)

// Generated by PyNSource http://www.andypatterns.com/index.php/products/pynsource/ 

unit unit_EventPlayAPI;

interface

uses
    unit_PlayAPI;

type

EventPlayAPI = class(PlayAPI)
public
    procedure GetCurrentValue(); virtual;
    procedure GetMaxValue(); virtual;
    procedure JumpToValue(); virtual;
    procedure _DeriveOtherPlayheadPositionsFrom(); virtual;
    procedure _TimeOfEventAt(); virtual;
    procedure _SetOtherPlayheadsTo(); virtual;
    procedure SynchroniseOtherPlayheads(); virtual;
end;


implementation

procedure EventPlayAPI.GetCurrentValue();
begin
end;

procedure EventPlayAPI.GetMaxValue();
begin
end;

procedure EventPlayAPI.JumpToValue();
begin
end;

procedure EventPlayAPI._DeriveOtherPlayheadPositionsFrom();
begin
end;

procedure EventPlayAPI._TimeOfEventAt();
begin
end;

procedure EventPlayAPI._SetOtherPlayheadsTo();
begin
end;

procedure EventPlayAPI.SynchroniseOtherPlayheads();
begin
end;


end.

