// Generated by PyNSource http://www.andypatterns.com/index.php/products/pynsource/ 

unit unit_TurnPlayAPI;

interface

uses
    unit_PlayAPI;

type

TurnPlayAPI = class(PlayAPI)
public
    procedure GetCurrentValue(); virtual;
    procedure GetMaxValue(); virtual;
    procedure JumpToValue(); virtual;
    procedure _DeriveOtherPlayheadPositionsFrom(); virtual;
    procedure _SetOtherPlayheadsTo(); virtual;
    procedure SynchroniseOtherPlayheads(); virtual;
end;


implementation

procedure TurnPlayAPI.GetCurrentValue();
begin
end;

procedure TurnPlayAPI.GetMaxValue();
begin
end;

procedure TurnPlayAPI.JumpToValue();
begin
end;

procedure TurnPlayAPI._DeriveOtherPlayheadPositionsFrom();
begin
end;

procedure TurnPlayAPI._SetOtherPlayheadsTo();
begin
end;

procedure TurnPlayAPI.SynchroniseOtherPlayheads();
begin
end;


end.

