
(*
  ModuleMethods = ['eventStrToList', 'show', 'ConvertShortTimeTupleToTimeStr', 'ConvertTimeStrToShortTimeTuple', 'getListItem', 'AAAAAA', 'PixelCoordToAbsQuad', 'AbsQuadCoordToPixel', 'ImportScenarioFile', 'repr_SortedDict', 'safeconvert', 'repr_SortedDictEx', 'DeriveScenarioFolderPath', 'PopFoldersTillFind', 'FilenameToFullScenarioPathName', 'roundit', 'TilequadToAbsquad', 'AbsquadToTilequad', 'eventStrToList_OLD', 'extractQualityInfo', 'chunkToTabbedChunk', 'asciiDate', 'TimePosToDateStr1943', 'asciiDate', 'TimePosToDateStr1943', 'cleanchunk', 'GetAllFromFile', 'CoordCompare', 'CoordXYonly', 'FormatSignalsDictForDisplay', 'suite', 'main']
*)

// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

unit unit_TestCase00;

interface

uses
    unit_TestCase;

type

TestCase00 = class(TestCase)
public
    simplestr : Variant;
    normalstr : Variant;

    procedure setUp(); virtual;
    procedure checkSimple(); virtual;
    procedure checkNormal(); virtual;
    procedure checkNormalOrder(); virtual;
    procedure checkSplitModernAT(); virtual;
    procedure checkSplitFutureAT(); virtual;
    procedure checkSplitHasWithDicts(); virtual;
    procedure checkasciiDate(); virtual;
    procedure checkasciiDateAgain(); virtual;
    procedure checkCoordCompare(); virtual;
    procedure checkRoundit(); virtual;
    procedure checkScenarioPath(); virtual;
    procedure checkFullPathForSingleFile(); virtual;
    procedure checkImportFileScenarioFile01(); virtual;
    procedure checkPixelToAbsQuadconversions(); virtual;
    procedure checkspeedofeventstrtolist(); virtual;
    procedure checkSortedDict_01(); virtual;
    procedure checkSortedDict_01a(); virtual;
end;


implementation

procedure TestCase00.setUp();
begin
end;

procedure TestCase00.checkSimple();
begin
end;

procedure TestCase00.checkNormal();
begin
end;

procedure TestCase00.checkNormalOrder();
begin
end;

procedure TestCase00.checkSplitModernAT();
begin
end;

procedure TestCase00.checkSplitFutureAT();
begin
end;

procedure TestCase00.checkSplitHasWithDicts();
begin
end;

procedure TestCase00.checkasciiDate();
begin
end;

procedure TestCase00.checkasciiDateAgain();
begin
end;

procedure TestCase00.checkCoordCompare();
begin
end;

procedure TestCase00.checkRoundit();
begin
end;

procedure TestCase00.checkScenarioPath();
begin
end;

procedure TestCase00.checkFullPathForSingleFile();
begin
end;

procedure TestCase00.checkImportFileScenarioFile01();
begin
end;

procedure TestCase00.checkPixelToAbsQuadconversions();
begin
end;

procedure TestCase00.checkspeedofeventstrtolist();
begin
end;

procedure TestCase00.checkSortedDict_01();
begin
end;

procedure TestCase00.checkSortedDict_01a();
begin
end;


end.

