// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

unit unit_PlayAPI;

interface

type

PlayAPI = class
public
    mediator : Variant;
    playhead : Variant;
    turnMgr : Variant;

    constructor Create;
    procedure IsEmpty(); virtual;
    procedure IsMoreToPlay(); virtual;
    procedure Start(); virtual;
    procedure Endd(); virtual;
    procedure Next(); virtual;
    procedure Previous(); virtual;
    procedure _GetCurrentPosition(); virtual;
    procedure GetCurrentValue(); virtual;
    procedure _GetMaxPosition(); virtual;
    procedure GetMaxValue(); virtual;
    procedure _JumpToPosition(); virtual;
    procedure JumpToValue(); virtual;
    procedure NotifyOfInsert(); virtual;
    procedure NotifyPositionNowValid(); virtual;
    procedure SynchroniseOtherPlayheads(); virtual;
    procedure _FindLastEventWithTimeElseMostRecentEventLessthanTime(); virtual;
    procedure _FindLastEventWithTimeElseMostRecentEventLessthanTime_ORI(); virtual;
    procedure _EnsureMaxTimeCorrespondsToMaxTurn(); virtual;
    procedure _GetPositionToSyncTo(); virtual;
end;


implementation

constructor PlayAPI.Create;
begin
end;

procedure PlayAPI.IsEmpty();
begin
end;

procedure PlayAPI.IsMoreToPlay();
begin
end;

procedure PlayAPI.Start();
begin
end;

procedure PlayAPI.Endd();
begin
end;

procedure PlayAPI.Next();
begin
end;

procedure PlayAPI.Previous();
begin
end;

procedure PlayAPI._GetCurrentPosition();
begin
end;

procedure PlayAPI.GetCurrentValue();
begin
end;

procedure PlayAPI._GetMaxPosition();
begin
end;

procedure PlayAPI.GetMaxValue();
begin
end;

procedure PlayAPI._JumpToPosition();
begin
end;

procedure PlayAPI.JumpToValue();
begin
end;

procedure PlayAPI.NotifyOfInsert();
begin
end;

procedure PlayAPI.NotifyPositionNowValid();
begin
end;

procedure PlayAPI.SynchroniseOtherPlayheads();
begin
end;

procedure PlayAPI._FindLastEventWithTimeElseMostRecentEventLessthanTime();
begin
end;

procedure PlayAPI._FindLastEventWithTimeElseMostRecentEventLessthanTime_ORI();
begin
end;

procedure PlayAPI._EnsureMaxTimeCorrespondsToMaxTurn();
begin
end;

procedure PlayAPI._GetPositionToSyncTo();
begin
end;


end.

