
(*
  ModuleMethods = ['suite', 'main']
*)

// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm 

unit unit_Playhead;

interface

type

Playhead = class
public
    Position : Variant;
    MaxPosition : Variant;

    constructor Create;
    procedure Clear(); virtual;
    procedure _ClipPositionToMax(); virtual;
    procedure _SetMaxItems(); virtual;
    procedure IsEmpty(); virtual;
    procedure IsMoreToPlay(); virtual;
    procedure NotifyPositionNowValid(); virtual;
    procedure NotifyOfInsert(); virtual;
    procedure GoStart(); virtual;
    procedure GoEnd(); virtual;
    procedure Go(); virtual;
    procedure GoNext(); virtual;
    procedure GoPrevious(); virtual;
end;


implementation

constructor Playhead.Create;
begin
end;

procedure Playhead.Clear();
begin
end;

procedure Playhead._ClipPositionToMax();
begin
end;

procedure Playhead._SetMaxItems();
begin
end;

procedure Playhead.IsEmpty();
begin
end;

procedure Playhead.IsMoreToPlay();
begin
end;

procedure Playhead.NotifyPositionNowValid();
begin
end;

procedure Playhead.NotifyOfInsert();
begin
end;

procedure Playhead.GoStart();
begin
end;

procedure Playhead.GoEnd();
begin
end;

procedure Playhead.Go();
begin
end;

procedure Playhead.GoNext();
begin
end;

procedure Playhead.GoPrevious();
begin
end;


end.

