// Generated by PyNSource http://www.atug.com/andypatterns/pynsource.htm
public class ParseMeTest {
    public  variant a;
    public  Blah b = new Blah();
    public  static variant d;
    public  variant e;
    public  Blah f = new Blah();
    public void __init__() {
    }
    public void IsInBattle() {
    }
    public void DoA() {
    }
}
