
/*
  ModuleMethods = ['suite', 'main']
*/
// Generated by PyNSource http://www.andypatterns.com/index.php/products/pynsource/ 

public class Playhead {
    public  variant Position;
    public  variant MaxPosition;
    public void __init__() {
    }
    public void Clear() {
    }
    public void _ClipPositionToMax() {
    }
    public void _SetMaxItems() {
    }
    public void IsEmpty() {
    }
    public void IsMoreToPlay() {
    }
    public void NotifyPositionNowValid() {
    }
    public void NotifyOfInsert() {
    }
    public void GoStart() {
    }
    public void GoEnd() {
    }
    public void Go() {
    }
    public void GoNext() {
    }
    public void GoPrevious() {
    }
}
