// Generated by PyNSource http://www.andypatterns.com/index.php/products/pynsource/ 

public class TestCase02 extends TestCase {
    public  PlayheadMediator _goto = new PlayheadMediator();
    public void setUp() {
    }
    public void CalcAmountOfTimeInStoryline() {
    }
    public void EnsureSanity() {
    }
    public void check01() {
    }
}
