// Generated by PyNSource http://www.andypatterns.com/index.php/products/pynsource/ 

public class TestCase01 extends TestCase {
    public  PlayheadMediator _goto = new PlayheadMediator();
    public void setUp() {
    }
    public void checkInit() {
    }
    public void checkStartNoItemsNormal() {
    }
    public void checkStartNoItemsAndGoPreviousNormal() {
    }
    public void checkStartOneItemNormal() {
    }
    public void checkBasicMovementSynch01Normal() {
    }
    public void checkBasicMovementSynch02Normal() {
    }
    public void checkMaxValue() {
    }
    public void checkJumpToAndValidateCurrentValueNormal() {
    }
    public void checkIsEmptyNormal() {
    }
    public void checkByTimeAndEventPositioningNormal() {
    }
    public void checkByTurnPositioningNormal() {
    }
    public void checkByTimeAndEventPositioningNormal02() {
    }
}
