
/*
  ModuleMethods = ['eventStrToList', 'show', 'ConvertShortTimeTupleToTimeStr', 'ConvertTimeStrToShortTimeTuple', 'getListItem', 'AAAAAA', 'PixelCoordToAbsQuad', 'AbsQuadCoordToPixel', 'ImportScenarioFile', 'repr_SortedDict', 'repr_SortedDictEx', 'DeriveScenarioFolderPath', 'FilenameToFullScenarioPathName', 'roundit', 'TilequadToAbsquad', 'AbsquadToTilequad', 'eventStrToList_OLD', 'extractQualityInfo', 'chunkToTabbedChunk', 'asciiDate', 'TimePosToDateStr1943', 'asciiDate', 'TimePosToDateStr1943', 'cleanchunk', 'GetAllFromFile', 'CoordCompare', 'CoordXYonly', 'FormatSignalsDictForDisplay', 'suite', 'main']
*/
// Generated by PyNSource http://www.andypatterns.com/index.php/products/pynsource/ 

public class TestCase00 extends TestCase {
    public  variant simplestr;
    public  variant normalstr;
    public void setUp() {
    }
    public void checkSimple() {
    }
    public void checkNormal() {
    }
    public void checkNormalOrder() {
    }
    public void checkSplitModernAT() {
    }
    public void checkSplitFutureAT() {
    }
    public void checkSplitHasWithDicts() {
    }
    public void checkasciiDate() {
    }
    public void checkasciiDateAgain() {
    }
    public void checkCoordCompare() {
    }
    public void checkRoundit() {
    }
    public void checkScenarioPath() {
    }
    public void checkFullPathForSingleFile() {
    }
    public void checkImportFileScenarioFile01() {
    }
    public void checkPixelToAbsQuadconversions() {
    }
    public void checkspeedofeventstrtolist() {
    }
    public void checkSortedDict_01() {
    }
    public void checkSortedDict_01a() {
    }
}
