// Generated by PyNSource http://www.andypatterns.com/index.php/products/pynsource/ 

public class TimePlayAPI extends PlayAPI {
    public void GetCurrentValue() {
    }
    public void GetMaxValue() {
    }
    public void JumpToValue() {
    }
    public void _DeriveOtherPlayheadPositionsFrom() {
    }
    public void _SetOtherPlayheadsTo() {
    }
    public void SynchroniseOtherPlayheads() {
    }
}
