// Generated by PyNSource http://www.andypatterns.com/index.php/products/pynsource/ 

public class UniqueList extends list {
    public void append() {
    }
    public void __add__() {
    }
    public void __iadd__() {
    }
}
