"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["pynsource-gui.py"]
DATA_FILES = ["dialogs/HelpWindow.html", "dialogs/help-images"]
OPTIONS = {'argv_emulation': False}
setup(app=APP, data_files=DATA_FILES, 
options={"py2app": OPTIONS}, setup_requires=["py2app"])
