name: pynsource
version: git
summary: 'Pynsource - reverse engineer Python source code into UML'
description: |
      UML tool for Python. Reverse engineer Python source code into UML.

grade: stable # devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # strict # use 'strict' once you have the right plugs and slots
base: core22
architectures:
  - build-on: [amd64]

apps:
  # You can also run with /snap/bin/pynsource. (hit TAB to autocomplete)
  pynsource:
    command: bin/pynsource
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - pulseaudio
      - home
      - gsettings
      - network
      - network-bind
      - removable-media
    desktop: usr/share/applications/pynsource.desktop
    extensions:
      # HINT: Adds plugs and changes environment variables when building and running
      - gnome
  pynsource-cli:
    command: bin/pynsource-cli
    plugs:
      - home
      - network
      - network-bind
      - removable-media

parts:
  copy-stuff:
    plugin: dump
    source: src/media
    organize:
      "*": lib/python3.10/site-packages/media/

  # To get the HelpWindow.html and the help-images folder into the snap
  copy-dialogs:
    plugin: dump
    source: src/dialogs/
    organize:
      "*": lib/python3.10/site-packages/dialogs/

  build-the-python-stuff-please:
    plugin: python
    source: .
    stage-packages:
      - libsdl2-2.0-0
    python-requirements:
      - .requirement-extras/requirements-linux-common.txt
    python-packages:
      - wxasync
      - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
    override-build: |
      install -Dm644 "snap/gui/pynsource.desktop" -t "$CRAFT_PART_INSTALL/usr/share/applications/"
      craftctl default
    organize:
      usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio/libpulsecommon-15.99.so: usr/lib/$CRAFT_ARCH_TRIPLET/libpulsecommon-15.99.so
