name: pynsource
version: git
summary: 'Pynsource - reverse engineer Python source code into UML'
grade: stable # devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core22
apps:
    pynsource:
        command: python3 $SNAP/pynsource-gui.py
        extensions: [gnome]
        plugs: [unity7, audio-playback, home, network]
parts:
  copy-stuff:
    plugin: dump
    source: ./src
  pynsource:
    plugin: python
    python-version: python3
    source: ./src
    python-packages:
        - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
        - wxasync
    python-requirements:
        - /root/project/.requirement-extras/requirements-linux-common.txt
