name: pynsource
version: git
summary: 'Pynsource - reverse engineer Python source code into UML'
description: |
      UML tool for Python. Reverse engineer Python source code into UML.

grade: stable # devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # strict # use 'strict' once you have the right plugs and slots
base: core22
architectures:
  - build-on: [amd64]

apps:
  # You can also run with /snap/bin/pynsource. (hit TAB to autocomplete)
  pynsource:
    command: bin/pynsource
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - pulseaudio
      - home
      - gsettings
      - network
      - network-bind
      - removable-media
    desktop: usr/share/applications/pynsource.desktop
    extensions:
      # HINT: Adds plugs and changes environment variables when building and running
      - gnome
  pynsource-cli:
    command: bin/pynsource-cli
    plugs:
      - home
      - network
      - network-bind
      - removable-media

#environment:
#  # WORKAROUND: Add python modules in Snap to search path
#  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages

parts:
  copy-stuff:
    plugin: dump
    source: src/media
    organize:
      "*": lib/python3.10/site-packages/media/

  # To get the HelpWindow.html and the help-images folder into the snap
  copy-dialogs:
    plugin: dump
    source: src/dialogs/
    organize:
      "*": lib/python3.10/site-packages/dialogs/

  build-the-python-stuff-please:
    plugin: python
    source: .

    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      # https://forum.snapcraft.io/t/python-plugin-gnome-3-extension-error/33396/8?u=oleksis
      # Seem to need this otherwise get ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH:+:$PATH}
      #- PYTHONPATH: /usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/root/.local/lib/python3.10/site-packages:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages:/root/project${PYTHONPATH:+:$PYTHONPATH}
    build-packages:
      - freeglut3
      - freeglut3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libnotify-dev
      - libsdl2-dev
      - libsm-dev
      - libtiff-dev
      - libwebkit2gtk-4.1-dev
      - libxtst-dev
      - libssl-dev
      - libpulse-dev
      - pkg-config
      - python3.10
      - python3.10-dev
      - libpython3.10-dev
      - python3.10-venv
      - python3-setuptools
      - python3-wheel
    stage-packages:
      - yt-dlp
      - freeglut3
      - ibus-gtk3
      - libasound2
      - libasyncns0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libdecor-0-0
      - libdeflate0
      - libepoxy0
      - libflac8
      - libglu1-mesa
      - libfontconfig1
      - libfribidi0
      - libgbm1
      - libgdk-pixbuf-2.0-0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libjbig0
      - libjpeg-turbo8
      - libnotify4
      - libogg0
      - libopus0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre2-32-0
      - libpixman-1-0
      - libpulse0
      - libsdl2-2.0-0
      - libsm6
      - libsndfile1
      - libthai0
      - libtiff5
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libwebp7
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      - libxxf86vm1
      - libatomic1
      - libdw1
      - libegl1
      - libenchant-2-2
      - libevdev2
      - libgl1
      - libglvnd0
      - libglx0
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgstreamer1.0-dev
      - libgudev-1.0-0
      - libharfbuzz-icu0
      - libhyphen0
      - libjavascriptcoregtk-4.1-0
      - libmanette-0.2-0
      - libopengl0
      - libopenjp2-7
      - liborc-0.4-0
      - libpsl5
      - libsecret-1-0
      - libsoup2.4-1
      - libunwind8
      - libwebkit2gtk-4.1-0
      - libwebpdemux2
      - libwoff1
      - libxslt1.1    
    python-requirements:
      - .requirement-extras/requirements-linux-common.txt
    python-packages:
      - wxasync
      - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
    override-build: |
      install -Dm644 "snap/gui/pynsource.desktop" -t "$CRAFT_PART_INSTALL/usr/share/applications/"
      craftctl default
    organize:
      usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio/libpulsecommon-15.99.so: usr/lib/$CRAFT_ARCH_TRIPLET/libpulsecommon-15.99.so
