name: Pynsource Snap
on:
  push:
    # branches: [ main ]
    tags: ['v*', 'pre*']

    # To trigger a build when above is set to tag
    # git tag -l
    # git tag -a v1.nn
    # git push --follow-tags
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: snapcore/action-build@v1
      id: snapcraft

    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
        
    # Uploads the snap to edge channel, test via: sudo snap refresh pynsource --edge
    # This fails because of symlink issues, hopefully snapcraft 7.3.1.post17+git8b3ed19b and later fix it
    # 
    # - name: Snap upload
    #   id: snapcraft_upload
    #   env:
    #     SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_store_credentials }}
    #   run: |
    #     snapcraft upload *.snap --release edge
