name: Pynsource Snap
on:
  push:
    # branches: [ main ]
    tags: ['v*', 'pre*']

    # To trigger a build when above is set to tag
    # git tag --l
    # git tag -a v1.nn
    # git push --follow-tags
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: snapcore/action-build@v1
      id: snapcraft

    - name: Modify Snap File to remove python symlinks - see https://forum.snapcraft.io/t/core22-gnome-extension-and-broken-symlinks/32900/4 
      run: |
        unsquashfs ${{ steps.snapcraft.outputs.snap }}
        rm squashfs-root/bin/python*
        snap pack squashfs-root

    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: squashfs-root.snap

    # Uploads the snap to edge channel, test via: sudo snap refresh pynsource --edge
    - name: Snap upload
      id: snapcraft_upload
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_store_credentials }}
      run: |
        snapcraft upload *.snap --release edge
